(function(){
var BASE_W=[{t:'LITE',name:'Lumentum Holdings Inc',sector:'Optical/AI',price:854.96,move:-0.67,event:'portfolio exposure',note:'verified quote snapshot',source:'finance-api snapshot 2026-05-30'},{t:'MRVL',name:'Marvell Technology Inc',sector:'Semiconductors/AI',price:205,move:.10,event:'portfolio position',note:'verified quote snapshot',source:'finance-api snapshot 2026-05-30'},{t:'TER',name:'Teradyne',sector:'Semicap equipment',price:144,move:2.4,event:'relative strength',note:'manual watch seed',source:'manual-seed'},{t:'SNOW',name:'Snowflake',sector:'Software',price:233.2,move:33.05,event:'earnings gap',note:'manual watch seed',source:'manual-seed'},{t:'CRWD',name:'CrowdStrike',sector:'Cybersecurity',price:646.2,move:.13,event:'quality watch',note:'manual watch seed',source:'manual-seed'}];
var BASE_P=[{t:'LITE',qty:8,pmc:1046.65,plan:'Hold. No mediazione. Valutare exit parziale su forza.'},{t:'MRVL',qty:15,pmc:199.5,plan:'Hold finche resta sopra PMC e non perde forza relativa.'}];
var ALIAS={MARVELL:'MRVL',LUMENTUM:'LITE','LUMENTUM HOLDINGS':'LITE','MARVELL TECHNOLOGY':'MRVL'};
var BAD_SOURCE=/fallback|synthetic|mock|demo|fixture|test|snapshot|manual-seed|v11-fallback/i;
function C(t){t=String(t||'').toUpperCase().trim().replace(/\.US$/,'');return ALIAS[t]||t}
function esc(x){return String(x==null?'':x).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function isRealTicker(t){t=C(t);return /^[A-Z][A-Z0-9.]{0,5}$/.test(t)&&!/^V\d+$/i.test(t)}
function L(k,f){try{var v=localStorage.getItem(k);return v?JSON.parse(v):f}catch(e){return f}}
var MARKET_URL=(function(){var src=document.currentScript&&document.currentScript.src;return src?new URL('../data/market.json',src).toString():'data/market.json'})();
var s={capital:Number(localStorage.getItem('lv10_capital')||73),watch:L('lv10_watch',BASE_W),portfolio:L('lv10_portfolio',BASE_P),history:L('lv10_history',[]),graveyard:L('lv10_graveyard',[]),settings:L('lv10_settings',{riskPct:.8,mode:'swing',api:''}),lastLive:localStorage.getItem('lv10_lastlive')||'manuale',market:L('lv10_market',{quotes:[],radar:[],news:[],sectorStrength:[],regime:{label:'selettivo',score:0}}),marketFetchError:localStorage.getItem('lv10_market_error')||'',marketUrl:MARKET_URL};
function save(){localStorage.setItem('lv10_capital',s.capital);localStorage.setItem('lv10_watch',JSON.stringify(s.watch));localStorage.setItem('lv10_portfolio',JSON.stringify(s.portfolio));localStorage.setItem('lv10_history',JSON.stringify(s.history.slice(0,100)));localStorage.setItem('lv10_graveyard',JSON.stringify(s.graveyard));localStorage.setItem('lv10_settings',JSON.stringify(s.settings));localStorage.setItem('lv10_lastlive',s.lastLive);localStorage.setItem('lv10_market',JSON.stringify(s.market||{}));localStorage.setItem('lv10_market_error',s.marketFetchError||'');localStorage.setItem('lv10_market_url',s.marketUrl||MARKET_URL)}
function fw(t){t=C(t);return (s.watch||[]).find(function(x){return C(x.t)===t})}
function own(t){t=C(t);return (s.portfolio||[]).some(function(p){return C(p.t)===t})}
function sourceOf(x){return (x&&String(x.source||x.quoteSource||x.provider||'').trim())||'nessuna fonte'}
function isValidQuote(x){if(!x)return false;var t=C(x.t||x.ticker||x.symbol),price=Number(x.price||x.close||x.last||0),src=sourceOf(x);return isRealTicker(t)&&Number.isFinite(price)&&price>0&&src!=='nessuna fonte'&&src!=='missing'&&!BAD_SOURCE.test(src)&&x.status!=='invalid'&&x.valid!==false&&!x.dataError}
function badReason(x){if(!x)return'quote mancante';var t=C(x.t||x.ticker||x.symbol),src=sourceOf(x),price=Number(x.price||x.close||x.last||0);if(!isRealTicker(t))return'ticker non reale o ID interno';if(BAD_SOURCE.test(src))return'fonte non valida: '+src;if(!Number.isFinite(price)||price<=0)return'prezzo mancante/non numerico';if(x.status==='invalid'||x.valid===false||x.dataError)return x.error||'quote marcata invalida';return'quote invalida'}
function quoteBadge(x){var src=sourceOf(x),bad=BAD_SOURCE.test(src);return'<span class="tag">Fonte: '+esc(src)+'</span>'+(bad?' <span class="pill bad">TEST DATA - LIVE DATA UNAVAILABLE</span>':(isValidQuote(x)?'':' <span class="pill bad">DATA WARNING</span>'))}
function repair(){s.watch=(s.watch||[]).map(function(x){x.t=C(x.t);return x}).filter(function(x){return isRealTicker(x.t)});s.portfolio=(s.portfolio||[]).map(function(x){x.t=C(x.t);return x}).filter(function(x){return isRealTicker(x.t)});BASE_W.forEach(function(b){var w=fw(b.t);if(!w)s.watch.push(JSON.parse(JSON.stringify(b)));else{if(!Number(w.price))w.price=b.price;if(!w.name)w.name=b.name;if(!w.sector||w.sector==='N/D')w.sector=b.sector;if(!w.source)w.source=b.source}});s.portfolio.forEach(function(p){if(!fw(p.t)){var b=BASE_W.find(function(x){return x.t===C(p.t)});s.watch.push(b?JSON.parse(JSON.stringify(b)):{t:C(p.t),name:C(p.t),sector:'Manual',price:0,move:0,event:'portfolio',note:'prezzo da inserire',source:'missing'})}});s.market=normalizeMarket(s.market||{});save()}
function applyMarket(m){if(!m)return;s.marketFetchError='';s.market=normalizeMarket(m);(s.market.quotes||[]).forEach(function(q){var t=C(q.ticker||q.symbol||q.t);if(!isRealTicker(t))return;var w=fw(t);if(!w){w={t:t,name:q.name||t,sector:q.sector||'Market scan',price:0,move:0,event:'market data',note:'',source:sourceOf(q)};s.watch.push(w)}w.name=q.name||w.name||t;w.sector=q.sector||w.sector||'Market scan';w.source=sourceOf(q);w.quoteSource=w.source;w.price=Number(q.price||q.close||q.last||0);w.move=Number(q.move||q.changePercent||q.percent||w.move||0);if(isValidQuote(q)){w.dataError=false;w.error=''}else{w.dataError=true;w.error=badReason(q)}});s.lastLive=(s.market.updatedAt?new Date(s.market.updatedAt).toLocaleString('it-IT'):new Date().toLocaleString('it-IT'))+' market.json';save()}
async function loadMarket(silent){var url=MARKET_URL+(MARKET_URL.indexOf('?')>=0?'&':'?')+'v='+Date.now();s.marketUrl=MARKET_URL;try{var r=await fetch(url);if(!r.ok)throw new Error('HTTP '+r.status+' loading '+MARKET_URL);var m=await r.json();if(!m||typeof m!=='object'||!Array.isArray(m.quotes))throw new Error('market.json schema invalido da '+MARKET_URL);applyMarket(m);if(!silent)alert('Dati market.json aggiornati');render()}catch(e){s.marketFetchError=e.message;save();if(!silent)alert('market.json non raggiungibile: '+e.message);render()}}
var $=function(q){return document.querySelector(q)},$$=function(q){return Array.prototype.slice.call(document.querySelectorAll(q))};
function us(n){return Math.round(Number(n)||0)+'$'}
function pc(n){return(Number(n)||0).toFixed(2)+'%'}
function N(x){x=x||{};var t=C(x.t||x.ticker||x.symbol);return{t:t,name:x.name||'',sector:x.sector||'N/D',price:Number(x.price||x.close||x.last)||0,move:Number(x.move||x.changePercent||x.percent)||0,event:x.event||'',note:x.note||'',source:sourceOf(x),dataError:!isValidQuote(Object.assign({},x,{t:t})),error:badReason(Object.assign({},x,{t:t})),owned:own(t),score:x.score}}
function score(x){x=N(x);if(x.dataError)return 0;if(x.score)return Number(x.score);var r=5;if(x.move>18)r=3.9;else if(x.move>12)r=4.8;else if(x.move>5)r=6.1;else if(x.move>2)r=7.6;else if(x.move>.8)r=6.7;else if(x.move<-4)r=3.6;else if(x.move<-2)r=4.2;var z=(x.event+' '+x.note).toLowerCase();if(z.indexOf('relative')>=0||z.indexOf('clean')>=0||z.indexOf('hold above')>=0)r+=.5;if(z.indexOf('gap')>=0||z.indexOf('earnings')>=0)r-=.5;if(z.indexOf('weak')>=0)r-=.8;if(x.owned&&x.t==='LITE')r-=.8;return Math.max(1,Math.min(9.5,Math.round(r*10)/10))}
function verdict(x){x=N(x);if(x.dataError)return'DATA ERROR';var r=score(x);if(x.t==='LITE')return'No mediare';if(x.move>12)return'FOMO alto';if(r>=7.5)return'Opportunita';if(r>=6.4)return'Watch forte';if(r>=5.2)return'Aspetta';if(x.move<-2)return'Debole';return'No trade'}
function typ(x){x=N(x);if(x.dataError)return'Quote invalida';if(x.t==='LITE')return'Recovery/Exit plan';if(x.move>12)return'Gap/FOMO';if(x.move>2)return'Intraday momentum';if(x.move<-2)return'Recovery fragile';return'Swing/Watch'}
function cc(r){return r>=7.2?'good':r>=5.8?'warn':'bad'}
function reason(x){x=N(x);if(x.dataError)return'DATA ERROR: '+esc(x.error)+'. Nessun piano o P/L generato da questa quote.';if(x.t==='LITE')return'Non mediare. Valutare vendita parziale solo su forza o switch verso leader.';if(x.owned)return'Posizione gia presente: gestire, non inseguire.';if(x.move>12)return'Anti-FOMO: movimento troppo verticale.';if(x.move>2)return'Momentum positivo: serve conferma e persistenza.';if(x.move<-2)return'Debolezza relativa: evitare coltelli che cadono.';return'Setup non abbastanza forte.'}
function card(x){x=N(x);var r=score(x),p=x.price||100;if(x.dataError)return'<article class="card data-error"><div class="head"><div><b class="ticker">'+esc(x.t)+'</b> <span class="tag">'+esc(x.name||x.sector)+'</span></div><span class="pill bad">DATA WARNING</span></div><p class="muted">'+esc(x.name||x.t)+' - '+quoteBadge(x)+'</p><div class="grid"><div class="metric"><small>Prezzo</small>'+(x.price?x.price:'LIVE DATA UNAVAILABLE')+'</div><div class="metric"><small>Move</small>'+pc(x.move)+'</div><div class="metric"><small>Score</small>'+(x.score?x.score+'/10':'N/D')+'</div></div><p class="bad">'+reason(x)+'</p></article>';return'<article class="card"><div class="head"><div><b class="ticker">'+esc(x.t)+'</b> <span class="tag">'+esc(x.sector)+'</span></div><span class="pill '+cc(r)+'">'+r+'/10</span></div><p class="muted">'+esc(x.name)+' - '+typ(x)+' - '+esc(x.event||'market scan')+'</p><p>'+quoteBadge(x)+'</p><div class="grid"><div class="metric"><small>Prezzo</small>'+x.price+'</div><div class="metric"><small>Move</small>'+pc(x.move)+'</div><div class="metric"><small>Verdetto</small>'+verdict(x)+'</div><div class="metric"><small>Size max</small>'+Math.max(1,Math.floor(s.capital*s.settings.riskPct/100/(p*.08)))+' az.</div></div><p>'+reason(x)+'</p><button data-action="log" data-t="'+esc(x.t)+'" data-v="'+esc(verdict(x))+'" data-s="'+r+'">Salva decisione</button></article>'}
function radarScore(q){return score(q)}
function normalizeQuote(q){q=Object.assign({},q||{});q.ticker=C(q.ticker||q.symbol||q.t);q.t=q.ticker;q.source=sourceOf(q);q.move=Number(q.move||q.changePercent||q.percent||0);q.price=Number(q.price||q.close||q.last||0);q.sector=q.sector||'Broad market';if(!isValidQuote(q)){q.status='invalid';q.dataError=true;q.error=badReason(q)}return q}
function normalizeMarket(m){m=m||{};var quotes=(m.quotes||[]).map(normalizeQuote).filter(function(q){return isRealTicker(q.ticker)});var goodQuotes=quotes.filter(isValidQuote);var payloadValid=Number(m.validQuotesCount);var validQuotesCount=Number.isFinite(payloadValid)&&payloadValid>=0?payloadValid:goodQuotes.length;var sectorStrength=m.sectorStrength&&m.sectorStrength.length?m.sectorStrength:buildSectorStrength(goodQuotes);var regime=m.regime||detectRegime(goodQuotes,sectorStrength);var best=sectorStrength[0]||null,worst=sectorStrength[sectorStrength.length-1]||null;var rawRadar=(m.radar&&m.radar.length?m.radar:goodQuotes.map(function(q){return Object.assign({},q,{score:radarScore(q),event:q.event||'market scan',note:q.move>2?'momentum candidate':q.move<-2?'weak relative':'neutral'})}));var radar=rawRadar.map(normalizeQuote).sort(function(a,b){return score(b)-score(a)});return Object.assign({},m,{quotes:quotes,radar:radar,sectorStrength:sectorStrength,regime:regime,bestSector:m.bestSector||best,worstSector:m.worstSector||worst,validQuotesCount:validQuotesCount,frontendValidQuotesCount:goodQuotes.length,universeSize:validQuotesCount})}
function buildSectorStrength(quotes){var by={};quotes.forEach(function(q){if(!isValidQuote(q))return;var k=q.sector||'Broad market';if(!by[k])by[k]={sector:k,count:0,avgMove:0,leaders:0,weak:0};by[k].count++;by[k].avgMove+=Number(q.move)||0;if(q.move>.8)by[k].leaders++;if(q.move<-1)by[k].weak++});return Object.keys(by).map(function(k){var x=by[k];x.avgMove=Number((x.avgMove/Math.max(1,x.count)).toFixed(2));x.score=Number((50+x.avgMove*8+x.leaders*2-x.weak*2).toFixed(1));return x}).sort(function(a,b){return b.score-a.score})}
function detectRegime(quotes,sectors){var priced=quotes.filter(isValidQuote),adv=priced.filter(function(q){return q.move>0}).length,lead=priced.filter(function(q){return q.move>.8}).length,weak=priced.filter(function(q){return q.move<-1}).length,breadth=priced.length?adv/priced.length:0,spread=(sectors[0]&&sectors[sectors.length-1])?sectors[0].avgMove-sectors[sectors.length-1].avgMove:0,label='selettivo';if(breadth>.58&&lead>weak*1.2)label='risk-on';else if(breadth<.42&&weak>lead)label='risk-off';else if(spread>3)label='rotazione settoriale';return{label:label,score:Number((breadth*100).toFixed(1)),breadth:Number((breadth*100).toFixed(1)),leaders:lead,weak:weak,priced:priced.length}}
function radarList(){var m=normalizeMarket(s.market||{});var all=[].concat(m.radar||[],s.watch||[]),seen={};return all.map(N).filter(function(x){if(!isRealTicker(x.t)||seen[x.t]||x.dataError)return false;seen[x.t]=1;return true}).sort(function(a,b){return score(b)-score(a)})}
function topRows(list){return list.slice(0,8).map(function(x){return'<div class="row"><div class="head"><b>'+esc(x.sector)+'</b><span class="pill '+(x.avgMove>=0?'good':'bad')+'">'+pc(x.avgMove)+'</span></div><div class="meta">Score '+x.score+' - '+x.count+' titoli - leader '+x.leaders+' / weak '+x.weak+'</div></div>'}).join('')}
function diagnosticsData(){var m=normalizeMarket(s.market||{}),quotes=m.quotes||[],valid=quotes.filter(isValidQuote),configured=(m.configuredTickers&&m.configuredTickers.length?m.configuredTickers:Object.keys((m.groups||{})).reduce(function(a,k){return a.concat(m.groups[k]||[])},[])).map(C).filter(isRealTicker),seenCfg={};configured=configured.filter(function(t){if(seenCfg[t])return false;seenCfg[t]=1;return true});var failedList=(m.failedQuotes&&m.failedQuotes.length?m.failedQuotes:quotes.filter(function(q){return !isValidQuote(q)}).map(function(q){return{ticker:C(q.ticker||q.t||q.symbol),sector:q.sector||'N/D',error:q.error||badReason(q)}}));var source=m.source||sourceOf(valid[0]||quotes[0]||{}),failed=failedList.length||Math.max(0,quotes.length-valid.length),minimum=Number(m.minimumValidQuotes||300),payloadValid=Number(m.validQuotesCount||0),frontendValid=valid.length,ok=!s.marketFetchError&&(m.quoteDownloadSuccess!==false)&&frontendValid>=minimum,status=m.quoteDownloadStatus||(ok?'success':'fail');var sectorCounts=(m.sectorCounts&&m.sectorCounts.length?m.sectorCounts:buildSectorStrength(valid).map(function(x){return{sector:x.sector,configured:0,valid:x.count,failed:0}}));var zeroSource=payloadValid||frontendValid?'none':(s.marketFetchError?'market.json fetch failed':'localStorage/default market has zero quotes');return{source:source||'nessuna fonte',status:status,ok:ok,valid:payloadValid||frontendValid,frontendValid:frontendValid,total:quotes.length,failed:failed,minimum:minimum,timestamp:m.updatedAt||'N/D',configured:configured,configuredCount:Number(m.configuredTickersCount||configured.length||quotes.length),validTickers:valid.map(function(q){return C(q.ticker||q.t||q.symbol)}).filter(isRealTicker),failedQuotes:failedList,sectorCounts:sectorCounts,error:s.marketFetchError||m.quoteDownloadError||'',marketUrl:s.marketUrl||MARKET_URL,radarCount:(m.radar||[]).length,sectorRankCount:(m.sectorStrength||[]).length,zeroSource:zeroSource}}
function shell(title,body){var nav=[['home','Home'],['portfolio','Portfolio'],['radar','Radar'],['leaders','Leaders'],['sectors','Sectors'],['more','Altro']];var h=location.hash.replace('#','')||'home';$('#app').innerHTML='<div class="shell"><header class="topbar"><div class="brand"><div><h1>'+esc(title)+'</h1><small>Ultimo update: '+esc(s.lastLive)+'</small></div><button id="refresh" class="ghost">Refresh</button></div></header><main class="page">'+body+'</main><nav class="bottomnav">'+nav.map(function(n){return'<a class="'+(h===n[0]?'active':'')+'" href="#'+n[0]+'">'+n[1]+'</a>'}).join('')+'</nav></div>';bindApi()}
function bindApi(){var r=$('#refresh');if(r)r.onclick=refreshApi}
function home(){var m=normalizeMarket(s.market||{}),best=m.bestSector||{},worst=m.worstSector||{},leaders=radarList().filter(function(x){return N(x).move>.8}).length,weak=radarList().filter(function(x){return N(x).move<-1}).length;shell('Lamborghini V11 Trading Desk','<section class="card hero"><div><p class="muted">Operating desk con universo reale, regime, settori e radar solo ticker di mercato.</p><h2>'+esc(m.regime.label)+'</h2><p>Regime breadth '+(m.regime.breadth||0)+'% - '+leaders+' leader / '+weak+' weak.</p></div><div class="rating">V11</div></section><section class="grid"><div class="metric"><small>Quote valide</small>'+(m.validQuotesCount||m.universeSize||0)+'</div><div class="metric"><small>Radar reale</small>'+(m.radar||[]).length+'</div><div class="metric"><small>Best sector</small>'+esc(best.sector||'N/D')+'</div><div class="metric"><small>Worst sector</small>'+esc(worst.sector||'N/D')+'</div></section><section class="card"><div class="section-title"><h3>Sector strength ranking</h3><a class="tag" href="#sectors">Apri</a></div>'+topRows(m.sectorStrength||[])+'</section><section class="card"><div class="section-title"><h3>Leader vs Weak</h3><a class="tag" href="#leaders">Dashboard</a></div><p>Best: '+esc(best.sector||'N/D')+' / Worst: '+esc(worst.sector||'N/D')+'. Usa il dashboard per confrontare forza relativa e fragilita.</p></section>')}
function portfolio(){shell('Portfolio','<div class="card"><label>Capital<input data-capital="1" type="number" value="'+esc(s.capital)+'"></label><p class="muted">Le posizioni sono modificabili; P/L e exit vengono calcolati solo con quote live valide.</p></div>'+(s.portfolio.map(function(p,i){var w=N(fw(p.t)||{t:p.t,source:'missing'}),valid=!w.dataError;return'<div class="card"><div class="head"><h2>'+esc(C(p.t))+'</h2><button class="danger" data-action="removePortfolio" data-i="'+i+'">X</button></div><p><b>'+esc(w.name||C(p.t))+'</b> '+quoteBadge(w)+'</p><div class="grid"><label>Ticker<input data-p="'+i+'" data-k="t" value="'+esc(C(p.t))+'"></label><label>Quantity<input data-p="'+i+'" data-k="qty" type="number" value="'+esc(p.qty)+'"></label><label>PMC<input data-p="'+i+'" data-k="pmc" type="number" step="0.01" value="'+esc(p.pmc)+'"></label><div class="metric"><small>Prezzo</small>'+(valid?w.price:'LIVE DATA UNAVAILABLE')+'</div><div class="metric"><small>P/L</small>'+(valid?us((w.price-Number(p.pmc||0))*Number(p.qty||0)):'LIVE DATA UNAVAILABLE')+'</div></div><label>Plan<textarea data-p="'+i+'" data-k="plan">'+esc(p.plan||'')+'</textarea></label><p>'+(valid?esc(p.plan):'<span class="bad">DATA WARNING: '+esc(w.error)+'. Nessun P/L o recovery plan generato.</span>')+'</p></div>'}).join('')||'<div class="card">Nessuna posizione.</div>'));$$('[data-p]').forEach(function(e){e.onchange=function(){var n=Number(e.getAttribute('data-p')),k=e.getAttribute('data-k');s.portfolio[n][k]=(k==='qty'||k==='pmc')?Number(e.value):(k==='t'?C(e.value):e.value);repair();portfolio()}});$$('[data-capital]').forEach(function(e){e.onchange=function(){s.capital=Number(e.value||0);save();portfolio()}})}
function radar(){var list=radarList();shell('Expanded Radar','<div class="card"><h2>'+list.length+' setup ordinati</h2><p class="muted">Radar con soli ticker reali; ID interni e quote fallback esclusi.</p></div>'+list.slice(0,80).map(card).join(''))}
function watch(){shell('Watchlist','<div class="card"><h2>Watchlist manuale</h2></div>'+s.watch.map(function(w,i){return'<div class="card"><input data-w="'+i+'" data-k="t" value="'+esc(C(w.t))+'"><input data-w="'+i+'" data-k="name" value="'+esc(w.name||'')+'"><input data-w="'+i+'" data-k="sector" value="'+esc(w.sector||'')+'"><input data-w="'+i+'" data-k="price" value="'+(w.price||0)+'"><input data-w="'+i+'" data-k="move" value="'+(w.move||0)+'"><p>'+quoteBadge(w)+'</p><button class="danger" data-action="removeWatch" data-i="'+i+'">Elimina</button></div>'}).join(''));$$('input[data-w]').forEach(function(e){e.onchange=function(){var n=Number(e.getAttribute('data-w')),k=e.getAttribute('data-k');s.watch[n][k]=(k==='price'||k==='move')?Number(e.value):(k==='t'?C(e.value):e.value);repair();watch()}})}
function marketLookup(t){t=C(t);var m=normalizeMarket(s.market||{}),all=[].concat(m.quotes||[],m.radar||[]);for(var i=0;i<all.length;i++){if(C(all[i].ticker||all[i].t||all[i].symbol)===t)return Object.assign({event:'quick analyze market.json'},all[i])}return null}
function quick(){shell('Quick Analyze','<div class="card"><input id="qt" placeholder="Ticker"><input id="qm" placeholder="Move %"><input id="qs" placeholder="Settore"><button id="qa">Analizza</button><div id="qr"></div></div>');$('#qa').onclick=function(){var t=C($('#qt').value),found=marketLookup(t),x=found||{t:t,sector:$('#qs').value||'Manual',price:100,move:Number(String($('#qm').value||0).replace(',','.')),event:'quick analyze manual fallback',source:'manual quick analyze'};$('#qr').innerHTML=(found?'<p class="good">Trovato in market.json: '+esc(t)+'</p>':'<p class="warn">Ticker non trovato in market.json: fallback manuale.</p>')+card(x)}}
function exit(){var opts=s.portfolio.map(function(p){return'<option value="'+esc(C(p.t))+'">'+esc(C(p.t))+'</option>'}).join('');shell('Exit Strategy Engine','<div class="card"><label>Titolo in crisi / da gestire<select id="exitTicker">'+opts+'</select></label><button id="buildExit">Genera strategia</button></div><div id="exitResult"></div>');$('#buildExit').onclick=function(){renderExit($('#exitTicker').value)};if(s.portfolio[0])renderExit(s.portfolio[0].t)}
function renderExit(t){t=C(t);var p=s.portfolio.find(function(x){return C(x.t)===t})||s.portfolio[0],w=N(fw(t)||{t:t,source:'missing'});if(!p)return;if(w.dataError){$('#exitResult').innerHTML='<div class="card data-error"><h2>'+esc(t)+' DATA WARNING</h2><p><b>'+esc(w.name||t)+'</b> '+quoteBadge(w)+'</p><p class="bad">LIVE DATA UNAVAILABLE: '+esc(w.error)+'. Exit Strategy bloccata: non vengono generati recovery plan, scenari di vendita o P/L da prezzi invalidi/test.</p></div>';return}var q=Number(p.qty||0),pr=Number(w.price||0),pmc=Number(p.pmc||0),pl=(pr-pmc)*q,a=Math.max(1,Math.floor(q*.25)),b=Math.max(1,Math.floor(q*.5));$('#exitResult').innerHTML='<div class="card"><h2>'+esc(t)+' Recovery / Exit</h2><p><b>'+esc(w.name||t)+'</b> '+quoteBadge(w)+'</p><div class="grid"><div class="metric"><small>Qty</small>'+q+'</div><div class="metric"><small>PMC</small>'+pmc+'</div><div class="metric"><small>Prezzo</small>'+pr+'</div><div class="metric"><small>P/L</small>'+us(pl)+'</div></div><p>Verdetto: '+(pl<0?'posizione in crisi. Decidere per scenari, non per panico.':'proteggi profitto con trailing e piano.')+'</p></div><div class="card"><h3>Scenario A - Tieni tutto</h3><p>Massima esposizione al recupero.</p></div><div class="card"><h3>Scenario B - Vendi '+a+' azioni</h3><p>Capitale liberato circa '+us(a*pr)+'. Restano '+(q-a)+' azioni.</p></div><div class="card"><h3>Scenario C - Vendi '+b+' azioni</h3><p>Capitale liberato circa '+us(b*pr)+'. Restano '+(q-b)+' azioni.</p></div>'}
var more=[['watch','Watchlist'],['quick','Quick Analyze'],['exit','Exit Strategy'],['events','Event Risk'],['graveyard','Trade Graveyard'],['history','Decision History'],['settings','Settings'],['macro','Macro Regime'],['diagnostics','Diagnostics']];
function morePage(){shell('Altro / Menu','<div class="card"><h2>Sezioni extra</h2>'+more.map(function(p){return'<p><a class="tag" href="#'+p[0]+'">'+p[1]+'</a></p>'}).join('')+'</div>')}
function leaders(){var list=radarList(),lead=list.filter(function(x){return N(x).move>.8}).slice(0,20),weak=list.filter(function(x){return N(x).move<-1}).sort(function(a,b){return N(a).move-N(b).move}).slice(0,20);shell('Leader vs Weak Dashboard','<div class="grid"><div class="metric"><small>Leader</small>'+lead.length+'</div><div class="metric"><small>Weak</small>'+weak.length+'</div></div><h3>Leader</h3>'+lead.map(card).join('')+'<h3>Weak</h3>'+weak.map(card).join(''))}
function sectors(){var m=normalizeMarket(s.market||{});shell('Sector Strength Ranking','<div class="card"><h2>Best sector: '+esc((m.bestSector||{}).sector||'N/D')+'</h2><p>Worst sector: '+esc((m.worstSector||{}).sector||'N/D')+'</p></div><div class="card">'+topRows(m.sectorStrength||[])+'</div>')}
function events(){var ns=(s.market&&s.market.news)||[];shell('Event Risk Engine',(ns.length?ns.map(function(n){return'<div class="card"><b>'+esc(C(n.ticker))+'</b><p>'+esc(n.title)+'</p></div>'}).join(''):'<div class="card">News non ancora disponibili.</div>'))}
function graveyard(){shell('Trade Graveyard','<div class="card"><textarea id="gt" placeholder="Errore/lezione"></textarea><button id="gb">Salva</button></div>'+s.graveyard.map(function(x,i){return'<div class="card"><p>'+esc(x)+'</p><button class="danger" data-action="removeGrave" data-i="'+i+'">Elimina</button></div>'}).join(''));$('#gb').onclick=function(){var v=$('#gt').value.trim();if(v)s.graveyard.unshift(v);save();graveyard()}}
function history(){shell('Decision History',s.history.map(function(x,i){return'<div class="card"><p>'+esc(x)+'</p><button class="danger" data-action="removeHistory" data-i="'+i+'">Elimina</button></div>'}).join('')||'<div class="card">Nessuna decisione.</div>')}
function settings(){shell('Settings','<div class="card"><label>Rischio % per trade<input id="risk" type="number" value="'+s.settings.riskPct+'"></label><label>Modalita<input id="mode" value="'+esc(s.settings.mode)+'"></label><label>API prezzi<input id="api" value="'+esc(s.settings.api||'')+'" placeholder="https://tuo-backend/quotes?symbols="></label><button id="saveSet">Salva settings</button></div><div class="card"><h3>Market data</h3><p>La app legge data/market.json, valida ticker reali, mostra fonte quote e blocca P/L/Exit se la fonte e invalida.</p></div>');$('#saveSet').onclick=function(){s.settings.riskPct=Number($('#risk').value||0);s.settings.mode=$('#mode').value;s.settings.api=$('#api').value;save();settings()}}
function macro(){var m=normalizeMarket(s.market||{});shell('Macro Regime','<div class="card"><h2>Regime: '+esc(m.regime.label)+'</h2><p>Breadth '+(m.regime.breadth||0)+'%. Leader '+(m.regime.leaders||0)+' / Weak '+(m.regime.weak||0)+'.</p><p>Solo leader veri. Evitare FOMO e mediazioni deboli.</p></div>')}
function diagnostics(){var d=diagnosticsData(),sectorRows=d.sectorCounts.map(function(x){return'<tr><td>'+esc(x.sector)+'</td><td>'+Number(x.configured||0)+'</td><td>'+Number(x.valid||x.count||0)+'</td><td>'+Number(x.failed||0)+'</td></tr>'}).join(''),failedRows=d.failedQuotes.slice(0,80).map(function(x){return'<tr><td>'+esc(C(x.ticker))+'</td><td>'+esc(x.sector||'N/D')+'</td><td>'+esc(x.error||'invalid quote')+'</td></tr>'}).join('');shell('Diagnostics','<div class="card"><h2>Market data diagnostics</h2><p class="muted">Stato diretto del download quote e della validazione dati mostrato nella UI.</p><div class="grid"><div class="metric"><small>Source used</small>'+esc(d.source)+'</div><div class="metric"><small>Quote download</small><span class="'+(d.ok?'good':'bad')+'">'+esc(d.status)+'</span></div><div class="metric"><small>Valid quotes</small>'+d.valid+' / '+d.minimum+'</div><div class="metric"><small>Configured tickers</small>'+d.configuredCount+'</div><div class="metric"><small>Total quotes</small>'+d.total+'</div><div class="metric"><small>Failed quotes</small>'+d.failed+'</div><div class="metric"><small>Timestamp</small>'+esc(d.timestamp)+'</div><div class="metric"><small>market.json URL</small>'+esc(d.marketUrl)+'</div><div class="metric"><small>Frontend valid quotes</small>'+d.frontendValid+'</div><div class="metric"><small>Radar entries</small>'+d.radarCount+'</div><div class="metric"><small>Sector ranking entries</small>'+d.sectorRankCount+'</div><div class="metric"><small>Zero source</small>'+esc(d.zeroSource)+'</div></div>'+(d.error?'<p class="bad">Errore: '+esc(d.error)+'</p>':'')+'</div><div class="card"><h3>Configured tickers</h3>'+(d.configured.length?'<p>'+d.configured.map(function(t){return'<span class="tag">'+esc(t)+'</span>'}).join('')+'</p>':'<p class="bad">Nessun ticker configurato.</p>')+'</div><div class="card"><h3>Valid quotes</h3>'+(d.validTickers.length?'<p>'+d.validTickers.map(function(t){return'<span class="tag">'+esc(t)+'</span>'}).join('')+'</p>':'<p class="bad">Nessun ticker scaricato con successo.</p>')+'</div><div class="card"><h3>Failed quotes</h3>'+(failedRows?'<table><thead><tr><th>Ticker</th><th>Sector</th><th>Error</th></tr></thead><tbody>'+failedRows+'</tbody></table>':'<p class="good">Nessuna quote fallita.</p>')+'</div><div class="card"><h3>Sector counts</h3><table><thead><tr><th>Sector</th><th>Configured</th><th>Valid</th><th>Failed</th></tr></thead><tbody>'+sectorRows+'</tbody></table></div>')}
async function refreshApi(){if(s.settings.api){var sy={};s.watch.forEach(function(x){if(isRealTicker(x.t))sy[C(x.t)]=1});s.portfolio.forEach(function(x){if(isRealTicker(x.t))sy[C(x.t)]=1});try{var r=await fetch(s.settings.api+encodeURIComponent(Object.keys(sy).join(','))),j=await r.json();applyMarket({updatedAt:new Date().toISOString(),quotes:j.quotes||j,radar:j.radar||[]});render();return}catch(e){alert('API non raggiungibile: '+e.message)}}loadMarket(false)}
document.addEventListener('click',function(e){var b=e.target.closest('[data-action]');if(!b)return;var a=b.getAttribute('data-action'),i=Number(b.getAttribute('data-i'));if(a==='removePortfolio'){s.portfolio.splice(i,1);repair();portfolio()}if(a==='removeWatch'){s.watch.splice(i,1);save();watch()}if(a==='removeGrave'){s.graveyard.splice(i,1);save();graveyard()}if(a==='removeHistory'){s.history.splice(i,1);save();history()}if(a==='log'){s.history.unshift(new Date().toLocaleString('it-IT')+' - '+b.getAttribute('data-t')+' - '+b.getAttribute('data-v')+' - '+b.getAttribute('data-s')+'/10');save();alert('Decisione salvata')}});
var routes={home:home,portfolio:portfolio,radar:radar,quick:quick,exit:exit,more:morePage,watch:watch,leaders:leaders,events:events,graveyard:graveyard,history:history,settings:settings,macro:macro,sectors:sectors,diagnostics:diagnostics};
function render(){repair();var p=location.hash.replace('#','')||'home';(routes[p]||home)()}
window.addEventListener('hashchange',render);try{repair();render();loadMarket(true)}catch(e){$('#app').innerHTML='<div class="page"><div class="notice">Errore V11: '+esc(e.message)+'</div></div>'}
})();
