(function(){
  var DEFAULT_WATCH = [
    {t:'LITE', name:'Lumentum', sector:'Optical/AI', price:897.9, move:-0.49, event:'portfolio exposure', note:'weak relative'},
    {t:'SNOW', name:'Snowflake', sector:'Software', price:233.2, move:33.05, event:'earnings gap', note:'too extended'},
    {t:'CRWD', name:'CrowdStrike', sector:'Cybersecurity', price:646.2, move:0.13, event:'quality watch', note:'neutral'},
    {t:'DLTR', name:'Dollar Tree', sector:'Retail defensive', price:112.5, move:17.38, event:'earnings catalyst', note:'gap risk'},
    {t:'TER', name:'Teradyne', sector:'Semicap equipment', price:144.0, move:2.4, event:'relative strength', note:'clean momentum'},
    {t:'CIEN', name:'Ciena', sector:'Networking', price:568.0, move:-2.42, event:'weak relative', note:'avoid knife'}
  ];
  var DEFAULT_PORT = [{t:'LITE', qty:8, pmc:1044.5, plan:'Hold/reduce. Non mediare se cambia poco il PMC.'}];
  function load(k,f){try{var v=localStorage.getItem(k); return v?JSON.parse(v):f;}catch(e){return f;}}
  var state = {
    capital: Number(localStorage.getItem('lv10_capital') || 2600),
    watch: load('lv10_watch', DEFAULT_WATCH),
    portfolio: load('lv10_portfolio', DEFAULT_PORT),
    history: load('lv10_history', []),
    graveyard: load('lv10_graveyard', []),
    settings: load('lv10_settings', {riskPct:0.8, mode:'swing', alerts:false, api:''})
  };
  var pages = [
    ['home','Home'],['portfolio','Portfolio'],['radar','Radar'],['watch','Watch'],['quick','Analyze'],['macro','Macro'],['sectors','Settori'],['leaders','Leader'],['events','Eventi'],['graveyard','Grave'],['history','Storico'],['settings','Set']
  ];
  function qs(s){return document.querySelector(s);} function qsa(s){return Array.prototype.slice.call(document.querySelectorAll(s));}
  function money(n){return Math.round(Number(n)||0)+'€';} function pct(n){return (Number(n)||0).toFixed(2)+'%';}
  function save(){localStorage.setItem('lv10_capital', String(state.capital));localStorage.setItem('lv10_watch', JSON.stringify(state.watch));localStorage.setItem('lv10_portfolio', JSON.stringify(state.portfolio));localStorage.setItem('lv10_history', JSON.stringify(state.history.slice(0,80)));localStorage.setItem('lv10_graveyard', JSON.stringify(state.graveyard));localStorage.setItem('lv10_settings', JSON.stringify(state.settings));}
  function owned(t){t=String(t||'').toUpperCase();return state.portfolio.some(function(p){return String(p.t).toUpperCase()===t;});}
  function norm(x){x=x||{}; return {t:String(x.t||'').toUpperCase(), name:x.name||'', sector:x.sector||'N/D', price:Number(x.price)||0, move:Number(x.move)||0, event:x.event||'', note:x.note||'', owned:owned(x.t)};}
  function score(x){x=norm(x);var r=5;if(x.move>18)r=3.9;else if(x.move>12)r=4.8;else if(x.move>5)r=6.1;else if(x.move>2)r=7.6;else if(x.move>0.8)r=6.7;else if(x.move<-4)r=3.6;else if(x.move<-2)r=4.2;var txt=(x.event+' '+x.note).toLowerCase();if(txt.indexOf('relative')>=0||txt.indexOf('clean')>=0)r+=0.5;if(txt.indexOf('earnings')>=0||txt.indexOf('gap')>=0)r-=0.5;if(txt.indexOf('weak')>=0||txt.indexOf('knife')>=0)r-=0.8;if(x.owned)r-=1.2;return Math.max(1,Math.min(9.5,Math.round(r*10)/10));}
  function verdict(x){var s=score(x);x=norm(x);if(x.move>12)return 'FOMO alto';if(s>=7.5)return 'Opportunita';if(s>=6.4)return 'Watch forte';if(s>=5.2)return 'Aspetta';if(x.move<-2)return 'Debole';return 'No trade';}
  function tradeType(x){x=norm(x);if(x.move>12)return 'Gap/FOMO';if(x.move>5)return 'Momentum esteso';if(x.move>2)return 'Intraday momentum';if(x.move>0.8)return 'Swing breve';if(x.move<-2)return 'Recovery fragile';return 'Watch';}
  function colorClass(s){return s>=7.2?'good':(s>=5.8?'warn':'bad');}
  function reason(x){x=norm(x);if(x.owned)return 'Portfolio-aware: sei gia esposto. Mediare solo se migliora molto il PMC.';if(x.move>12)return 'Anti-FOMO: movimento troppo verticale. Attendere base o pullback.';if(x.move>2)return 'Momentum positivo non eccessivo: serve conferma, volumi e persistenza.';if(x.move<-2)return 'Debolezza relativa: evitare coltelli che cadono salvo reversal chiaro.';return 'Setup non abbastanza forte per impegnare capitale.';}
  function size(x){var s=score(x);x=norm(x);var mult=0.08;if(tradeType(x).indexOf('Recovery')>=0)mult=0.025;if(tradeType(x).indexOf('Intraday')>=0)mult=0.055;if(tradeType(x).indexOf('Gap')>=0)mult=0.018;if(x.owned)mult*=0.45;return Math.max(20,Math.min(state.capital*0.18,state.capital*mult*s/10));}
  function levels(x){x=norm(x);var p=x.price||100;return {entry:(p*1.004).toFixed(2), stop:(p*0.982).toFixed(2), target:(p*1.035).toFixed(2)};}
  function topPick(){return state.watch.slice().sort(function(a,b){return score(b)-score(a);})[0] || {t:'-',move:0};}
  function synth(){var t=topPick();return 'Sintesi: '+t.t+' '+score(t)+'/10 · '+verdict(t)+' · capitale '+money(state.capital);}
  function nav(){return '<nav class="bottomnav">'+pages.map(function(p){var active=(location.hash.replace('#','')||'home')===p[0]?'active':'';return '<a class="'+active+'" href="#'+p[0]+'"><b>'+p[1]+'</b></a>';}).join('')+'</nav>';}
  function shell(title, body){qs('#app').innerHTML='<div class="shell"><header class="topbar"><small>Lamborghini V10 Trading Desk</small><h1>'+title+'</h1><p>'+synth()+'</p></header><main class="page">'+body+'</main>'+nav()+'</div>';}
  function card(x){x=norm(x);var s=score(x), lv=levels(x);return '<article class="card"><div class="head"><div><b class="ticker">'+x.t+'</b><span class="tag">'+x.sector+'</span></div><span class="pill '+colorClass(s)+'">'+s+'/10</span></div><p class="muted">'+x.name+' · '+tradeType(x)+' · '+(x.event||'nessun evento')+'</p><div class="grid"><div class="metric"><small>Move</small>'+pct(x.move)+'</div><div class="metric"><small>Verdict</small>'+verdict(x)+'</div><div class="metric"><small>Size max</small>'+money(size(x))+'</div><div class="metric"><small>Durata</small>'+(s>=7?'1-5h / 2-5gg':'attesa')+'</div><div class="metric"><small>Entry</small>'+lv.entry+'</div><div class="metric"><small>Stop</small>'+lv.stop+'</div><div class="metric"><small>Target</small>'+lv.target+'</div><div class="metric"><small>Risk</small>'+state.settings.riskPct+'%</div></div><p>'+reason(x)+'</p><button class="ghost" data-action="log" data-t="'+x.t+'" data-v="'+verdict(x)+'" data-s="'+s+'">Salva decisione</button></article>';}
  function home(){var top=state.watch.slice().sort(function(a,b){return score(b)-score(a);}).slice(0,4);var t=top[0]||{};shell('Home Command Center','<section class="card hero"><div><small>Decision Agent</small><h2>'+t.t+'</h2><p>'+verdict(t)+' · '+reason(t)+'</p></div><div class="rating '+colorClass(score(t))+'">'+score(t)+'/10</div></section><div class="grid"><div class="metric"><small>Capitale libero</small>'+money(state.capital)+'</div><div class="metric"><small>Regime</small>Selettivo</div><div class="metric"><small>Alert</small>'+(state.settings.alerts?'ON':'OFF')+'</div><div class="metric"><small>Mode</small>'+state.settings.mode+'</div></div><h3>Top Radar</h3>'+top.map(card).join(''));}
  function portfolio(){var totalPl=0;var rows=state.portfolio.map(function(p,i){var q=state.watch.find(function(x){return String(x.t).toUpperCase()===String(p.t).toUpperCase();});var price=q?Number(q.price):0;var pl=(price-Number(p.pmc||0))*Number(p.qty||0);totalPl+=pl;return '<div class="card"><div class="head"><b>'+p.t+'</b><span class="pill '+(pl>=0?'good':'bad')+'">'+pl.toFixed(0)+'$</span></div><div class="grid"><input data-p="'+i+'" data-k="t" value="'+(p.t||'')+'"><input data-p="'+i+'" data-k="qty" type="number" value="'+(p.qty||0)+'"><input data-p="'+i+'" data-k="pmc" type="number" value="'+(p.pmc||0)+'"><input data-p="'+i+'" data-k="plan" value="'+(p.plan||'')+'"></div><p class="muted">Prezzo radar '+(price||'-')+' · P/L calcolato da PMC</p><button class="danger" data-action="removePortfolio" data-i="'+i+'">Rimuovi</button></div>';}).join('');shell('Portfolio','<div class="card"><label>Capitale libero<input id="cap" type="number" value="'+state.capital+'"></label><button id="addPosBtn" type="button">+ Posizione</button></div><div class="grid"><div class="metric"><small>P/L totale</small>'+totalPl.toFixed(0)+'$</div><div class="metric"><small>Posizioni</small>'+state.portfolio.length+'</div></div>'+rows);qs('#cap').oninput=function(e){state.capital=Number(e.target.value||0);save();};qs('#addPosBtn').onclick=addPortfolio;qsa('[data-p]').forEach(function(inp){inp.onchange=function(e){var i=Number(e.target.getAttribute('data-p'));var k=e.target.getAttribute('data-k');state.portfolio[i][k]=(k==='qty'||k==='pmc')?Number(e.target.value):String(e.target.value).toUpperCase();save();portfolio();};});}
  function addPortfolio(){state.portfolio.unshift({t:'NUOVO',qty:1,pmc:0,plan:'Scrivi piano operativo'});save();portfolio();setTimeout(function(){window.scrollTo(0,180);},80);}
  function removePortfolio(i){state.portfolio.splice(i,1);save();portfolio();}
  function radar(){var list=state.watch.slice().sort(function(a,b){return score(b)-score(a);});shell('Opportunity Radar','<div class="card"><h3>Scanner operativo</h3><p>Radar API-ready. Ora usa watchlist manuale; poi collegheremo feed reali.</p></div>'+list.map(card).join(''));}
  function watch(){var rows=state.watch.map(function(x,i){return '<div class="card"><div class="grid"><input data-w="'+i+'" data-k="t" value="'+x.t+'"><input data-w="'+i+'" data-k="sector" value="'+x.sector+'"><input data-w="'+i+'" data-k="price" type="number" value="'+x.price+'"><input data-w="'+i+'" data-k="move" type="number" value="'+x.move+'"><input data-w="'+i+'" data-k="event" value="'+x.event+'"><input data-w="'+i+'" data-k="note" value="'+x.note+'"></div><button class="danger" data-action="removeWatch" data-i="'+i+'">Rimuovi</button></div>';}).join('');shell('Watchlist','<div class="card"><button id="addWatchBtn" type="button">+ Titolo</button></div>'+rows);qs('#addWatchBtn').onclick=addWatch;qsa('[data-w]').forEach(function(inp){inp.onchange=function(e){var i=Number(e.target.getAttribute('data-w'));var k=e.target.getAttribute('data-k');state.watch[i][k]=(k==='price'||k==='move')?Number(e.target.value):e.target.value;save();watch();};});}
  function addWatch(){state.watch.unshift({t:'NEW',name:'',sector:'Manual',price:100,move:0,event:'manual',note:''});save();watch();}
  function removeWatch(i){state.watch.splice(i,1);save();watch();}
  function quick(){shell('Quick Analyze','<div class="card"><input id="qt" placeholder="Ticker es. TER"><input id="qn" placeholder="Nome/news opzionale"><input id="qm" placeholder="Move % es. 2.4"><input id="qs" placeholder="Settore"><button id="qa" type="button">Analizza</button><div id="qr"></div></div>');qs('#qa').onclick=function(){var x={t:qs('#qt').value,name:qs('#qn').value,sector:qs('#qs').value||'Manual',price:100,move:Number(String(qs('#qm').value||'0').replace(',','.')),event:'quick analyze',note:''};qs('#qr').innerHTML=card(x);logDecision(x.t,verdict(x),score(x),false);};}
  function macro(){shell('Macro & Market Regime','<div class="card"><h2>Regime: selettivo</h2><p>Operare solo su setup con persistenza. Evitare inseguimenti dopo gap estremi.</p></div><div class="card"><h3>Framework</h3><p>Macro, settore, leader/laggard, catalyst, timing, size, decisione finale.</p></div>');}
  function sectors(){var m={};state.watch.forEach(function(x){if(!m[x.sector])m[x.sector]=[];m[x.sector].push(x);});shell('Sector Rotation',Object.keys(m).map(function(s){return '<div class="card"><h3>'+s+'</h3><p>'+m[s].map(function(x){return x.t+' '+pct(x.move)+' ('+score(x)+'/10)';}).join(' · ')+'</p></div>';}).join(''));}
  function leaders(){var l=state.watch.filter(function(x){return x.move>2;}).sort(function(a,b){return score(b)-score(a);});var w=state.watch.filter(function(x){return x.move<-2;});shell('Relative Strength','<h3>Leader</h3>'+(l.map(card).join('')||'<div class="card">Nessun leader.</div>')+'<h3>Weak / evitare</h3>'+(w.map(card).join('')||'<div class="card">Nessun debole.</div>'));}
  function events(){shell('Event Risk Engine',state.watch.map(function(x){return '<div class="card"><div class="head"><b>'+x.t+'</b><span class="tag">'+x.event+'</span></div><p>'+((x.event||'').toLowerCase().indexOf('earnings')>=0?'Evento gia prezzato: rischio FOMO.':'Monitorare news, calendario e volumi.')+'</p></div>';}).join(''));}
  function graveyard(){shell('Trade Graveyard','<div class="card"><textarea id="gt" placeholder="Errore/lezione trade"></textarea><button id="gb" type="button">Salva lezione</button></div>'+state.graveyard.map(function(x,i){return '<div class="card"><p>'+x+'</p><button class="danger" data-action="removeGrave" data-i="'+i+'">Elimina</button></div>';}).join(''));qs('#gb').onclick=function(){var v=qs('#gt').value.trim();if(v)state.graveyard.unshift(v);save();graveyard();};}
  function history(){shell('Decision History',state.history.map(function(x,i){return '<div class="card"><p>'+x+'</p><button class="danger" data-action="removeHistory" data-i="'+i+'">Elimina</button></div>';}).join('')||'<div class="card">Nessuna decisione ancora.</div>');}
  function settings(){shell('Settings','<div class="card"><label>Rischio % per trade<input id="risk" type="number" value="'+state.settings.riskPct+'"></label><label>Modalita<input id="mode" value="'+state.settings.mode+'"></label><label>API endpoint futuro<input id="api" value="'+state.settings.api+'" placeholder="https://..."></label><button id="saveSet" type="button">Salva settings</button></div><div class="card"><h3>Stato dati</h3><p>Versione stabile API-ready. Prossimo step: feed reale.</p></div>');qs('#saveSet').onclick=function(){state.settings.riskPct=Number(qs('#risk').value||0);state.settings.mode=qs('#mode').value;state.settings.api=qs('#api').value;save();settings();};}
  function logDecision(t,v,s,alertIt){state.history.unshift(new Date().toLocaleString('it-IT')+' · '+t+' · '+v+' · '+s+'/10');save();if(alertIt!==false)alert('Decisione salvata');}
  document.addEventListener('click',function(e){var b=e.target.closest('[data-action]');if(!b)return;var a=b.getAttribute('data-action');var i=Number(b.getAttribute('data-i'));if(a==='removePortfolio')removePortfolio(i);if(a==='removeWatch')removeWatch(i);if(a==='removeGrave'){state.graveyard.splice(i,1);save();graveyard();}if(a==='removeHistory'){state.history.splice(i,1);save();history();}if(a==='log')logDecision(b.getAttribute('data-t'),b.getAttribute('data-v'),Number(b.getAttribute('data-s')),true);});
  var routes={home:home,portfolio:portfolio,radar:radar,watch:watch,quick:quick,macro:macro,sectors:sectors,leaders:leaders,events:events,graveyard:graveyard,history:history,settings:settings};
  function render(){var p=location.hash.replace('#','')||'home';(routes[p]||home)();}
  window.addEventListener('hashchange',render);render();
})();