(function(){
  var DEFAULT_WATCH=[
    {t:'LITE',name:'Lumentum',sector:'Optical/AI',price:831.62,move:-3.37,event:'portfolio exposure',note:'weak relative'},
    {t:'MRVL',name:'Marvell',sector:'Semiconductors/AI',price:202.41,move:-1.18,event:'portfolio position',note:'hold above PMC'},
    {t:'TER',name:'Teradyne',sector:'Semicap equipment',price:144,move:2.4,event:'relative strength',note:'clean momentum'},
    {t:'SNOW',name:'Snowflake',sector:'Software',price:233.2,move:33.05,event:'earnings gap',note:'too extended'},
    {t:'CRWD',name:'CrowdStrike',sector:'Cybersecurity',price:646.2,move:0.13,event:'quality watch',note:'neutral'}
  ];
  var DEFAULT_PORT=[
    {t:'LITE',qty:8,pmc:1046.65,plan:'Hold. No mediazione. Valutare exit parziale su forza.'},
    {t:'MRVL',qty:15,pmc:199.5,plan:'Hold finche resta sopra PMC e non perde forza relativa.'}
  ];
  function load(k,f){try{var v=localStorage.getItem(k);return v?JSON.parse(v):f}catch(e){return f}}
  var state={capital:Number(localStorage.getItem('lv10_capital')||73),watch:load('lv10_watch',DEFAULT_WATCH),portfolio:load('lv10_portfolio',DEFAULT_PORT),history:load('lv10_history',[]),graveyard:load('lv10_graveyard',[]),settings:load('lv10_settings',{riskPct:0.8,mode:'swing',alerts:false,api:''}),lastLive:localStorage.getItem('lv10_lastlive')||'manuale'};
  var pages=[['home','Home'],['portfolio','Portfolio'],['radar','Radar'],['watch','Watch'],['quick','Analyze'],['exit','Exit'],['leaders','Leader'],['events','Eventi'],['graveyard','Grave'],['history','Storico'],['settings','Set']];
  var $=function(s){return document.querySelector(s)};var $$=function(s){return Array.prototype.slice.call(document.querySelectorAll(s))};
  function money(n){return Math.round(Number(n)||0)+'€'}function usd(n){return Math.round(Number(n)||0)+'$'}function pct(n){return(Number(n)||0).toFixed(2)+'%'}
  function save(){localStorage.setItem('lv10_capital',state.capital);localStorage.setItem('lv10_watch',JSON.stringify(state.watch));localStorage.setItem('lv10_portfolio',JSON.stringify(state.portfolio));localStorage.setItem('lv10_history',JSON.stringify(state.history.slice(0,100)));localStorage.setItem('lv10_graveyard',JSON.stringify(state.graveyard));localStorage.setItem('lv10_settings',JSON.stringify(state.settings));localStorage.setItem('lv10_lastlive',state.lastLive)}
  function owned(t){t=String(t||'').toUpperCase();return state.portfolio.some(function(p){return String(p.t||'').toUpperCase()===t})}
  function findWatch(t){t=String(t||'').toUpperCase();return state.watch.find(function(x){return String(x.t||'').toUpperCase()===t})}
  function norm(x){x=x||{};return{t:String(x.t||'').toUpperCase(),name:x.name||'',sector:x.sector||'N/D',price:Number(x.price)||0,move:Number(x.move)||0,event:x.event||'',note:x.note||'',owned:owned(x.t)}}
  function score(x){x=norm(x);var r=5;if(x.move>18)r=3.9;else if(x.move>12)r=4.8;else if(x.move>5)r=6.1;else if(x.move>2)r=7.6;else if(x.move>0.8)r=6.7;else if(x.move<-4)r=3.6;else if(x.move<-2)r=4.2;var txt=(x.event+' '+x.note).toLowerCase();if(txt.indexOf('relative')>=0||txt.indexOf('clean')>=0||txt.indexOf('hold above')>=0)r+=0.5;if(txt.indexOf('earnings')>=0||txt.indexOf('gap')>=0)r-=0.5;if(txt.indexOf('weak')>=0||txt.indexOf('knife')>=0)r-=0.8;if(x.owned&&x.t==='LITE')r-=0.8;return Math.max(1,Math.min(9.5,Math.round(r*10)/10))}
  function verdict(x){x=norm(x);var s=score(x);if(x.t==='LITE')return'No mediare';if(x.move>12)return'FOMO alto';if(s>=7.5)return'Opportunita';if(s>=6.4)return'Watch forte';if(s>=5.2)return'Aspetta';if(x.move<-2)return'Debole';return'No trade'}
  function tradeType(x){x=norm(x);if(x.t==='LITE')return'Recovery/Exit plan';if(x.move>12)return'Gap/FOMO';if(x.move>5)return'Momentum esteso';if(x.move>2)return'Intraday momentum';if(x.move>0.8)return'Swing breve';if(x.move<-2)return'Recovery fragile';return'Watch'}
  function cls(s){return s>=7.2?'good':(s>=5.8?'warn':'bad')}function size(x){var s=score(x);x=norm(x);var m=0.08;if(tradeType(x).indexOf('Recovery')>=0)m=0.025;if(tradeType(x).indexOf('Intraday')>=0)m=0.055;if(tradeType(x).indexOf('Gap')>=0)m=0.018;if(x.owned)m*=0.45;return Math.max(0,Math.min(state.capital*0.18,state.capital*m*s/10))}
  function reason(x){x=norm(x);if(x.t==='LITE')return'Posizione debole e pesante: non mediare. Valutare vendita parziale solo su forza o switch verso leader migliore.';if(x.owned)return'Portfolio-aware: posizione gia presente. Gestire, non inseguire.';if(x.move>12)return'Anti-FOMO: movimento troppo verticale. Attendere base o pullback.';if(x.move>2)return'Momentum positivo: valido solo con conferma e persistenza.';if(x.move<-2)return'Debolezza relativa: evitare coltelli che cadono.';return'Setup non abbastanza forte per impegnare capitale.'}
  function levels(x){x=norm(x);var p=x.price||100;return{entry:(p*1.004).toFixed(2),stop:(p*0.982).toFixed(2),target:(p*1.035).toFixed(2)}}
  function card(x){x=norm(x);var s=score(x),lv=levels(x);return'<article class="card"><div class="head"><div><b class="ticker">'+x.t+'</b> <span class="tag">'+x.sector+'</span></div><span class="pill '+cls(s)+'">'+s+'/10</span></div><p class="muted">'+x.name+' - '+tradeType(x)+' - '+(x.event||'nessun evento')+'</p><div class="grid"><div class="metric"><small>Prezzo</small>'+x.price+'</div><div class="metric"><small>Move</small>'+pct(x.move)+'</div><div class="metric"><small>Verdict</small>'+verdict(x)+'</div><div class="metric"><small>Size max</small>'+money(size(x))+'</div><div class="metric"><small>Entry</small>'+lv.entry+'</div><div class="metric"><small>Stop</small>'+lv.stop+'</div><div class="metric"><small>Target</small>'+lv.target+'</div><div class="metric"><small>Risk</small>'+state.settings.riskPct+'%</div></div><p>'+reason(x)+'</p><button class="ghost" data-action="log" data-t="'+x.t+'" data-v="'+verdict(x)+'" data-s="'+s+'">Salva decisione</button></article>'}
  function topPick(){return state.watch.slice().sort(function(a,b){return score(b)-score(a)})[0]||{t:'-',move:0}}
  function synth(){var t=topPick();return'Sintesi: '+t.t+' '+score(t)+'/10 - '+verdict(t)+' - capitale '+money(state.capital)}
  function nav(){return'<nav class="bottomnav">'+pages.map(function(p){var a=(location.hash.replace('#','')||'home')===p[0]?'active':'';return'<a class="'+a+'" href="#'+p[0]+'"><b>'+p[1]+'</b></a>'}).join('')+'</nav>'}
  function shell(title,body){$('#app').innerHTML='<div class="shell"><header class="topbar"><small>Lamborghini V10 Definitiva</small><h1>'+title+'</h1><p>'+synth()+'</p></header><main class="page">'+body+'</main>'+nav()+'</div>'}
  function portfolioMetrics(){var total=0,value=0;state.portfolio.forEach(function(p){var w=findWatch(p.t);var price=w?Number(w.price):0;value+=price*Number(p.qty||0);total+=(price-Number(p.pmc||0))*Number(p.qty||0)});return{pl:total,value:value}}
  function liveBox(){return'<div class="notice"><b>Dati prezzi:</b> '+state.lastLive+'<br><button id="refreshApi" type="button">Aggiorna da API</button><small> Richiede endpoint in Settings.</small></div>'}
  function bindApi(){var b=$('#refreshApi');if(b)b.onclick=refreshFromApi}
  function home(){var pm=portfolioMetrics();var top=state.watch.slice().sort(function(a,b){return score(b)-score(a)}).slice(0,3);shell('Home Command Center',liveBox()+'<section class="card hero"><div><small>COSA FARE ADESSO</small><h2>Gestisci</h2><p>Hold MRVL. Non mediare LITE. Cerca solo setup A+.</p></div><div class="rating '+cls(score(top[0]))+'">'+score(top[0])+'/10</div></section><div class="grid"><div class="metric"><small>Capitale libero</small>'+money(state.capital)+'</div><div class="metric"><small>P/L portafoglio</small>'+usd(pm.pl)+'</div><div class="metric"><small>Valore posizioni</small>'+usd(pm.value)+'</div><div class="metric"><small>Regime</small>Selettivo</div></div><div class="card"><h3>FAI</h3><p>Gestisci MRVL. Proteggi capitale. Valuta LITE solo con piano, non con panico.</p><h3>NON FARE</h3><p>Non mediare LITE. Non forzare intraday per recuperare.</p></div><h3>Top Radar</h3>'+top.map(card).join(''));bindApi()}
  function portfolio(){var pm=portfolioMetrics();var rows=state.portfolio.map(function(p,i){var w=findWatch(p.t);var price=w?Number(w.price):0;var pl=(price-Number(p.pmc||0))*Number(p.qty||0);return'<div class="card"><div class="head"><b>'+p.t+'</b><span class="pill '+(pl>=0?'good':'bad')+'">'+pl.toFixed(0)+'$</span></div><div class="grid"><input data-p="'+i+'" data-k="t" value="'+(p.t||'')+'"><input data-p="'+i+'" data-k="qty" type="number" value="'+(p.qty||0)+'"><input data-p="'+i+'" data-k="pmc" type="number" value="'+(p.pmc||0)+'"><input data-p="'+i+'" data-k="plan" value="'+(p.plan||'')+'"></div><p class="muted">Prezzo radar/API '+(price||'-')+' - P/L da PMC</p><button class="danger" data-action="removePortfolio" data-i="'+i+'">Rimuovi</button></div>'}).join('');shell('Portfolio Command Center',liveBox()+'<div class="card"><label>Capitale libero<input id="cap" type="number" value="'+state.capital+'"></label><button id="addPosBtn" type="button">+ Posizione</button></div><div class="grid"><div class="metric"><small>Valore posizioni</small>'+usd(pm.value)+'</div><div class="metric"><small>P/L totale</small>'+usd(pm.pl)+'</div><div class="metric"><small>Posizioni</small>'+state.portfolio.length+'</div><div class="metric"><small>Cash</small>'+money(state.capital)+'</div></div>'+rows);$('#cap').oninput=function(e){state.capital=Number(e.target.value||0);save()};$('#addPosBtn').onclick=function(){state.portfolio.unshift({t:'NUOVO',qty:1,pmc:0,plan:'Piano operativo'});save();portfolio()};$$('[data-p]').forEach(function(inp){inp.onchange=function(e){var i=Number(e.target.getAttribute('data-p')),k=e.target.getAttribute('data-k');state.portfolio[i][k]=(k==='qty'||k==='pmc')?Number(e.target.value):String(e.target.value).toUpperCase();save();portfolio()}});bindApi()}
  function radar(){var list=state.watch.slice().sort(function(a,b){return score(b)-score(a)});shell('Opportunity Radar',liveBox()+'<div class="notice">Solo setup A+. Prezzi aggiornabili da API configurata.</div>'+list.map(card).join(''));bindApi()}
  function watch(){var rows=state.watch.map(function(x,i){return'<div class="card"><div class="grid"><input data-w="'+i+'" data-k="t" value="'+x.t+'"><input data-w="'+i+'" data-k="sector" value="'+x.sector+'"><input data-w="'+i+'" data-k="price" type="number" value="'+x.price+'"><input data-w="'+i+'" data-k="move" type="number" value="'+x.move+'"><input data-w="'+i+'" data-k="event" value="'+x.event+'"><input data-w="'+i+'" data-k="note" value="'+x.note+'"></div><button class="danger" data-action="removeWatch" data-i="'+i+'">Rimuovi</button></div>'}).join('');shell('Watchlist',liveBox()+'<div class="card"><button id="addWatchBtn" type="button">+ Titolo</button></div>'+rows);$('#addWatchBtn').onclick=function(){state.watch.unshift({t:'NEW',name:'',sector:'Manual',price:100,move:0,event:'manual',note:''});save();watch()};$$('[data-w]').forEach(function(inp){inp.onchange=function(e){var i=Number(e.target.getAttribute('data-w')),k=e.target.getAttribute('data-k');state.watch[i][k]=(k==='price'||k==='move')?Number(e.target.value):e.target.value;save();watch()}});bindApi()}
  function quick(){shell('Quick Analyze','<div class="card"><input id="qt" placeholder="Ticker es. TER"><input id="qn" placeholder="Nome/news opzionale"><input id="qm" placeholder="Move % es. 2.4"><input id="qs" placeholder="Settore"><button id="qa" type="button">Analizza</button><div id="qr"></div></div>');$('#qa').onclick=function(){var x={t:$('#qt').value,name:$('#qn').value,sector:$('#qs').value||'Manual',price:100,move:Number(String($('#qm').value||'0').replace(',','.')),event:'quick analyze',note:''};$('#qr').innerHTML=card(x)}}
  function exitPage(){var opts=state.portfolio.map(function(p){return'<option value="'+p.t+'">'+p.t+'</option>'}).join('');shell('Exit Strategy Engine','<div class="card"><label>Titolo in crisi / da gestire<select id="exitTicker">'+opts+'</select></label><button id="buildExit" type="button">Genera strategia</button></div><div id="exitResult"></div>');$('#buildExit').onclick=function(){renderExit($('#exitTicker').value)};if(state.portfolio[0])renderExit(state.portfolio[0].t)}
  function renderExit(t){var p=state.portfolio.find(function(x){return String(x.t).toUpperCase()===String(t).toUpperCase()})||state.portfolio[0];var w=findWatch(p.t)||{price:0};var qty=Number(p.qty||0),price=Number(w.price||0),pmc=Number(p.pmc||0),pl=(price-pmc)*qty;var sell25=Math.max(1,Math.floor(qty*0.25)),sell50=Math.max(1,Math.floor(qty*0.5));$('#exitResult').innerHTML='<div class="card"><h2>'+p.t+' Recovery / Exit</h2><div class="grid"><div class="metric"><small>Qty</small>'+qty+'</div><div class="metric"><small>PMC</small>'+pmc+'</div><div class="metric"><small>Prezzo</small>'+price+'</div><div class="metric"><small>P/L</small>'+usd(pl)+'</div></div><p>Verdetto: '+(pl<0?'posizione in crisi. Decidere per scenari, non per panico.':'posizione non in crisi: gestire trailing e protezione profitto.')+'</p></div><div class="card"><h3>Scenario A - Tieni tutto</h3><p>Massima esposizione al recupero, ma capitale bloccato e rischio psicologico alto.</p></div><div class="card"><h3>Scenario B - Vendi '+sell25+' azioni</h3><p>Capitale liberato circa '+usd(sell25*price)+'. Restano '+(qty-sell25)+' azioni. Riduci pressione senza abbandonare la tesi.</p></div><div class="card"><h3>Scenario C - Vendi '+sell50+' azioni</h3><p>Capitale liberato circa '+usd(sell50*price)+'. Restano '+(qty-sell50)+' azioni. Switch piu deciso verso setup migliori.</p></div><div class="card"><h3>Regola V10</h3><p>Vendere pezzi ha senso solo se il capitale va su setup A+, non per recuperare emotivamente.</p></div>'}
  function leaders(){var l=state.watch.filter(function(x){return x.move>0.8}).sort(function(a,b){return score(b)-score(a)});var w=state.watch.filter(function(x){return x.move<-1});shell('Leader vs Weak','<h3>Leader</h3>'+(l.map(card).join('')||'<div class="card">Nessun leader.</div>')+'<h3>Weak</h3>'+(w.map(card).join('')||'<div class="card">Nessun debole.</div>'))}
  function events(){shell('Event Risk Engine',state.watch.map(function(x){return'<div class="card"><div class="head"><b>'+x.t+'</b><span class="tag">'+x.event+'</span></div><p>Monitorare news, calendario, earnings, Fed, Nvidia, dazi e geopolitica.</p></div>'}).join(''))}
  function graveyard(){shell('Trade Graveyard','<div class="card"><textarea id="gt" placeholder="Errore/lezione trade"></textarea><button id="gb" type="button">Salva lezione</button></div>'+state.graveyard.map(function(x,i){return'<div class="card"><p>'+x+'</p><button class="danger" data-action="removeGrave" data-i="'+i+'">Elimina</button></div>'}).join(''));$('#gb').onclick=function(){var v=$('#gt').value.trim();if(v)state.graveyard.unshift(v);save();graveyard()}}
  function history(){shell('Decision History',state.history.map(function(x,i){return'<div class="card"><p>'+x+'</p><button class="danger" data-action="removeHistory" data-i="'+i+'">Elimina</button></div>'}).join('')||'<div class="card">Nessuna decisione ancora.</div>')}
  function settings(){shell('Settings','<div class="card"><label>Rischio % per trade<input id="risk" type="number" value="'+state.settings.riskPct+'"></label><label>Modalita<input id="mode" value="'+state.settings.mode+'"></label><label>API prezzi<input id="api" value="'+state.settings.api+'" placeholder="https://tuo-backend/quotes?symbols="></label><button id="saveSet" type="button">Salva settings</button></div><div class="card"><h3>Tempo reale</h3><p>Per dati real-time seri serve un backend/API. Qui puoi inserire un endpoint che restituisce JSON: { quotes:[{ticker, price, move}] }.</p></div>');$('#saveSet').onclick=function(){state.settings.riskPct=Number($('#risk').value||0);state.settings.mode=$('#mode').value;state.settings.api=$('#api').value;save();settings()}}
  function macro(){shell('Macro Regime','<div class="card"><h2>Regime: selettivo</h2><p>Solo leader veri. Evitare FOMO, mediazioni deboli e recovery senza conferma.</p></div>')}
  async function refreshFromApi(){if(!state.settings.api){alert('Inserisci prima un endpoint API nei Settings.');return}var symbols={};state.watch.forEach(function(x){symbols[x.t]=true});state.portfolio.forEach(function(x){symbols[x.t]=true});var list=Object.keys(symbols).join(',');try{var r=await fetch(state.settings.api+encodeURIComponent(list));var j=await r.json();var arr=j.quotes||j;arr.forEach(function(q){var t=String(q.ticker||q.symbol||q.t||'').toUpperCase();if(!t)return;var w=findWatch(t);if(!w){w={t:t,name:t,sector:'API',price:0,move:0,event:'api price',note:''};state.watch.push(w)}w.price=Number(q.price||q.close||q.last||w.price);w.move=Number(q.move||q.changePercent||q.percent||w.move)});state.lastLive=new Date().toLocaleString('it-IT')+' da API';save();render()}catch(e){alert('API non raggiungibile o formato non valido: '+e.message)}}
  document.addEventListener('click',function(e){var b=e.target.closest('[data-action]');if(!b)return;var a=b.getAttribute('data-action'),i=Number(b.getAttribute('data-i'));if(a==='removePortfolio'){state.portfolio.splice(i,1);save();portfolio()}if(a==='removeWatch'){state.watch.splice(i,1);save();watch()}if(a==='removeGrave'){state.graveyard.splice(i,1);save();graveyard()}if(a==='removeHistory'){state.history.splice(i,1);save();history()}if(a==='log'){state.history.unshift(new Date().toLocaleString('it-IT')+' - '+b.getAttribute('data-t')+' - '+b.getAttribute('data-v')+' - '+b.getAttribute('data-s')+'/10');save();alert('Decisione salvata')}});
  var routes={home:home,portfolio:portfolio,radar:radar,watch:watch,quick:quick,exit:exitPage,leaders:leaders,events:events,graveyard:graveyard,history:history,settings:settings,macro:macro,sectors:macro};
  function render(){var p=location.hash.replace('#','')||'home';(routes[p]||home)()}window.addEventListener('hashchange',render);try{render()}catch(e){$('#app').innerHTML='<div class="page"><div class="notice">Errore V10: '+e.message+'</div></div>'}
})();