(function(){
  'use strict';

  var MARKET_KEY='lv10_market';
  var PORTFOLIO_KEY='lv10_portfolio';
  var FX_KEY='lv10_fx_profile';
  var OVERRIDE_KEY='lv10_portfolio_price_overrides';
  var DEFAULT_EUR_USD=1.14;
  var DEFAULT_OVERRIDES={COHR:{price:376.99,source:'portfolio-override'},NOW:{price:112.45,source:'portfolio-override'},DDOG:{price:234.11,source:'portfolio-override'},FCEL:{price:17.33,source:'portfolio-override'},INCY:{price:102.38,source:'portfolio-override'}};

  function $(q,r){return (r||document).querySelector(q)}
  function clean(v){return String(v==null?'':v).trim()}
  function ticker(v){return clean(v).toUpperCase().replace(/\.US$/,'').replace(/[^A-Z0-9.]/g,'')}
  function num(v){if(typeof v==='number')return Number.isFinite(v)?v:0;var s=clean(v).replace(/\s/g,'');if(s.indexOf(',')>=0&&s.indexOf('.')>=0)s=s.replace(/\./g,'').replace(',','.');else s=s.replace(',','.');var n=Number(s.replace(/[^0-9.\-]/g,''));return Number.isFinite(n)?n:0}
  function load(k,f){try{var v=localStorage.getItem(k);return v?JSON.parse(v):f}catch(e){return f}}
  function save(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch(e){}}
  function pct(v){var n=Number(v)||0;return (n>0?'+':'')+n.toFixed(2)+'%'}
  function usd(v){return (Number(v)||0).toLocaleString('it-IT',{maximumFractionDigits:2})+' $'}
  function cls(score){return score>=70?'good':score>=45?'warn':'bad'}
  function page(){return (location.hash.replace('#','')||'home')}
  function fx(){var f=load(FX_KEY,null);var eurUsd=f&&num(f.eurUsd)>0?num(f.eurUsd):DEFAULT_EUR_USD;if(!f)save(FX_KEY,{baseCurrency:'EUR',quoteCurrency:'USD',eurUsd:eurUsd,manual:true});return {eurUsd:eurUsd,usdEur:1/eurUsd}}
  function overrides(){var o=load(OVERRIDE_KEY,null);if(!o){save(OVERRIDE_KEY,DEFAULT_OVERRIDES);o=DEFAULT_OVERRIDES}return Object.assign({},DEFAULT_OVERRIDES,o||{})}
  function market(){return load(MARKET_KEY,{quotes:[],sectorStrength:[],regime:{label:'selettivo'}})}
  function quotes(){var m=market(),ov=overrides(),out={};(m.quotes||[]).forEach(function(q){var t=ticker(q.ticker||q.t||q.symbol),p=num(q.price||q.close||q.last);if(t&&p>0)out[t]=Object.assign({},q,{_ticker:t,_price:p})});Object.keys(ov).forEach(function(k){var t=ticker(k),p=num(ov[k].price);if(t&&p>0)out[t]=Object.assign({},out[t]||{},ov[k],{ticker:t,t:t,symbol:t,price:p,close:p,last:p,_ticker:t,_price:p,source:ov[k].source||'portfolio-override',valid:true})});return out}
  function portfolio(){return (load(PORTFOLIO_KEY,[])||[]).map(function(p){return Object.assign({},p,{t:ticker(p.t),qty:num(p.qty),pmc:num(p.pmc)})}).filter(function(p){return p.t&&p.qty>0&&p.pmc>0})}
  function rows(){var q=quotes();return portfolio().map(function(p){var live=q[p.t]?num(q[p.t]._price):0,invested=p.qty*p.pmc,value=live?p.qty*live:0,pl=live?(live-p.pmc)*p.qty:0,plPct=live&&p.pmc?(live/p.pmc-1)*100:0;return {p:p,q:q[p.t],live:live,invested:invested,value:value,pl:pl,plPct:plPct,sector:q[p.t]&&q[p.t].sector||'Manual'}})}
  function sectorScore(name){var m=market(),list=m.sectorStrength||[],s=list.find(function(x){return clean(x.sector||x.name)===clean(name)})||{};var score=num(s.score);if(score)return Math.max(0,Math.min(100,score));var avg=num(s.avgMove);return Math.max(0,Math.min(100,50+avg*8+num(s.leaders)*2-num(s.weak)*2))}
  function macroAgent(){var m=market(),r=m.regime||{},breadth=num(r.breadth||r.score),leaders=num(r.leaders),weak=num(r.weak),valid=num(m.validQuotesCount||m.frontendValidQuotesCount);var score=50;if(breadth)score+=((breadth-50)*.6);score+=Math.min(15,leaders*.15);score-=Math.min(20,weak*.18);if(valid>=300)score+=5;score=Math.max(0,Math.min(100,Math.round(score)));var label=score>=70?'Risk On':score>=45?'Neutral':'Risk Off';var verdict=score>=70?'Mercato favorevole, ma evitare FOMO e titoli già tirati.':score>=45?'Mercato selettivo: prima gestire le posizioni, poi eventuali nuovi ingressi.':'Mercato difensivo: proteggere capitale e non mediare titoli deboli.';return {score:score,label:label,verdict:verdict,breadth:breadth,leaders:leaders,weak:weak}}
  function sectorAgent(){var m=market();var list=(m.sectorStrength||[]).slice().map(function(s){return {sector:s.sector||s.name||'N/D',score:sectorScore(s.sector||s.name),avgMove:num(s.avgMove),leaders:num(s.leaders),weak:num(s.weak)}}).sort(function(a,b){return b.score-a.score}).slice(0,8);if(!list.length)list=[{sector:'Semiconductors',score:55},{sector:'Software',score:55},{sector:'Healthcare/biotech',score:50},{sector:'Energy',score:50}];return list}
  function positionVerdict(r,macro){var score=50;score+=Math.max(-25,Math.min(25,r.plPct*.9));if(r.q&&String(r.q.source||'').indexOf('override')>=0)score+=3;if(/FCEL/i.test(r.p.t))score-=22;if(/INCY/i.test(r.p.t))score+=12;if(/COHR|DDOG|NOW/i.test(r.p.t)&&macro.score<55)score-=7;score=Math.max(0,Math.min(100,Math.round(score)));var action='Mantieni, non incrementare';if(score>=70)action='Mantieni / lascia lavorare';if(score<50)action='Monitorare, niente incremento';if(score<38)action='Difensiva: ridurre su rimbalzi';if(score<28)action='Speculativa: nessuna mediazione';var why=[];why.push(r.plPct>=0?'sopra PMC':'sotto PMC');if(macro.score<55)why.push('macro selettiva');if(/FCEL/i.test(r.p.t))why.push('titolo molto speculativo');if(/INCY/i.test(r.p.t))why.push('miglior profilo relativo');return {score:score,action:action,why:why.join(' · ')}}
  function htmlMetric(k,v,c){return '<div class="metric"><small>'+k+'</small>'+(c?'<span class="'+c+'">'+v+'</span>':v)+'</div>'}
  function macroHtml(){var a=macroAgent();return '<section id="v16-macro-agent" class="card"><div class="section-title"><h3>V16 Macro Agent</h3><span class="pill '+cls(a.score)+'">'+a.label+' '+a.score+'/100</span></div><div class="grid">'+htmlMetric('Breadth',a.breadth?a.breadth+'%':'N/D')+htmlMetric('Leader',a.leaders)+htmlMetric('Weak',a.weak)+htmlMetric('Aggressività',a.score>=70?'Alta controllata':a.score>=45?'Selettiva':'Bassa',cls(a.score))+'</div><p>'+a.verdict+'</p></section>'}
  function sectorHtml(){var list=sectorAgent();return '<section id="v16-sector-agent" class="card"><div class="section-title"><h3>Sector Rotation Agent</h3><span class="tag">Prezzi + forza relativa</span></div>'+list.map(function(s,i){return '<div class="row"><b>'+(i+1)+'. '+s.sector+'</b><span class="pill '+cls(s.score)+'">'+Math.round(s.score)+'</span></div>'}).join('')+'</section>'}
  function doctorHtml(){var macro=macroAgent(),rs=rows();if(!rs.length)return '';return '<section id="v16-position-doctor" class="card"><div class="section-title"><h3>Position Doctor</h3><span class="tag">Portfolio</span></div>'+rs.map(function(r){var v=positionVerdict(r,macro);return '<article class="card mini"><div class="section-title"><h3>'+r.p.t+'</h3><span class="pill '+cls(v.score)+'">'+v.score+'/100</span></div><div class="grid">'+htmlMetric('Live',usd(r.live))+htmlMetric('PMC',usd(r.p.pmc))+htmlMetric('P/L',pct(r.plPct),r.plPct>=0?'good':'bad')+htmlMetric('Azione',v.action,cls(v.score))+'</div><p>'+v.why+'</p></article>'}).join('')+'</section>'}
  function synthActionLine(r,macro){var v=positionVerdict(r,macro),emoji=v.score>=70?'🟢':v.score>=45?'🟡':'🔴';return '<div class="row"><b>'+emoji+' '+r.p.t+'</b><span>'+v.action+'</span></div>'}
  function synthHtml(){var macro=macroAgent(),rs=rows();var best=rs.slice().sort(function(a,b){return b.plPct-a.plPct})[0],worst=rs.slice().sort(function(a,b){return a.plPct-b.plPct})[0];var header='Gestione selettiva: niente nuove mediazioni impulsive.';if(macro.score>=70)header='Mercato favorevole, ma comprare solo setup puliti e non estesi.';if(macro.score<45)header='Difesa capitale: ridurre rischio e aspettare conferme.';var lines=rs.map(function(r){return synthActionLine(r,macro)}).join('');var risk='<p><b>Regola V16:</b> non mediare titoli deboli senza conferma macro + settore + catalyst. Prima gestire rischio, poi cercare opportunità.</p>';return '<section id="v16-synth-agent" class="card hero"><div><h2>Cosa fare oggi</h2><p>'+header+'</p>'+lines+'<p><b>Migliore:</b> '+(best?best.p.t+' '+pct(best.plPct):'N/D')+' · <b>Più delicata:</b> '+(worst?worst.p.t+' '+pct(worst.plPct):'N/D')+'</p>'+risk+'</div><div class="rating">V16</div></section>'}
  function opportunityHtml(){var sectors=sectorAgent(),top=sectors[0];return '<section id="v16-opportunity-agent" class="card"><div class="section-title"><h3>Opportunity Radar</h3><span class="tag">Bozza decisionale</span></div><p>Priorità: cercare titoli non troppo estesi nei settori con score alto. Settore più forte ora: <b>'+(top?top.sector:'N/D')+'</b>.</p><p>Prossimo step: collegare news, earnings, macro calendar e catalyst specifici prima di dare un voto operativo definitivo.</p></section>'}
  function injectHome(){if(page()!=='home')return;var old=$('#v16-synth-agent');if(old)old.remove();var pg=$('.page');if(!pg)return;var wrap=document.createElement('div');wrap.innerHTML=synthHtml()+macroHtml()+sectorHtml()+doctorHtml()+opportunityHtml();var first=pg.firstElementChild;if(first)pg.insertBefore(wrap,first);else pg.appendChild(wrap)}
  function injectPortfolio(){if(page()!=='portfolio')return;if($('#v16-position-doctor'))return;var pg=$('.page');if(!pg)return;var wrap=document.createElement('div');wrap.innerHTML=doctorHtml()+opportunityHtml();pg.appendChild(wrap)}
  function run(){setTimeout(function(){injectHome();injectPortfolio()},350)}
  window.addEventListener('load',run);window.addEventListener('hashchange',run);new MutationObserver(run).observe(document.documentElement,{childList:true,subtree:true});
})();
