(function(){
  'use strict';

  var MARKET_KEY='lv10_market';
  var PORTFOLIO_KEY='lv10_portfolio';
  var OVERRIDE_KEY='lv10_portfolio_price_overrides';
  var DEFAULT_OVERRIDES={COHR:{price:376.99,source:'portfolio-override'},NOW:{price:112.45,source:'portfolio-override'},DDOG:{price:234.11,source:'portfolio-override'},FCEL:{price:17.33,source:'portfolio-override'},INCY:{price:102.38,source:'portfolio-override'}};
  var lastHomeKey='';
  var lastPortfolioKey='';

  function $(q,r){return (r||document).querySelector(q)}
  function clean(v){return String(v==null?'':v).trim()}
  function ticker(v){return clean(v).toUpperCase().replace(/\.US$/,'').replace(/[^A-Z0-9.]/g,'')}
  function num(v){if(typeof v==='number')return Number.isFinite(v)?v:0;var s=clean(v).replace(/\s/g,'');if(s.indexOf(',')>=0&&s.indexOf('.')>=0)s=s.replace(/\./g,'').replace(',','.');else s=s.replace(',','.');var n=Number(s.replace(/[^0-9.\-]/g,''));return Number.isFinite(n)?n:0}
  function load(k,f){try{var v=localStorage.getItem(k);return v?JSON.parse(v):f}catch(e){return f}}
  function pct(v){var n=Number(v)||0;return (n>0?'+':'')+n.toFixed(2)+'%'}
  function usd(v){return (Number(v)||0).toLocaleString('it-IT',{maximumFractionDigits:2})+' $'}
  function cls(score){return score>=70?'good':score>=45?'warn':'bad'}
  function page(){return (location.hash.replace('#','')||'home')}
  function market(){return load(MARKET_KEY,{quotes:[],sectorStrength:[],regime:{label:'selettivo'}})}
  function overrides(){return Object.assign({},DEFAULT_OVERRIDES,load(OVERRIDE_KEY,{})||{})}
  function quotes(){var m=market(),ov=overrides(),out={};(m.quotes||[]).forEach(function(q){var t=ticker(q.ticker||q.t||q.symbol),p=num(q.price||q.close||q.last);if(t&&p>0)out[t]=Object.assign({},q,{_ticker:t,_price:p})});Object.keys(ov).forEach(function(k){var t=ticker(k),p=num(ov[k].price);if(t&&p>0)out[t]=Object.assign({},out[t]||{},ov[k],{ticker:t,t:t,symbol:t,price:p,close:p,last:p,_ticker:t,_price:p,source:ov[k].source||'portfolio-override',valid:true})});return out}
  function portfolio(){return (load(PORTFOLIO_KEY,[])||[]).map(function(p){return Object.assign({},p,{t:ticker(p.t),qty:num(p.qty),pmc:num(p.pmc)})}).filter(function(p){return p.t&&p.qty>0&&p.pmc>0})}
  function rows(){var q=quotes();return portfolio().map(function(p){var live=q[p.t]?num(q[p.t]._price):0,plPct=live&&p.pmc?(live/p.pmc-1)*100:0;return {p:p,q:q[p.t],live:live,plPct:plPct,sector:q[p.t]&&q[p.t].sector||'Manual'}})}
  function sectorScore(name){var m=market(),list=m.sectorStrength||[],s=list.find(function(x){return clean(x.sector||x.name)===clean(name)})||{};var score=num(s.score);if(score)return Math.max(0,Math.min(100,score));var avg=num(s.avgMove);return Math.max(0,Math.min(100,50+avg*8+num(s.leaders)*2-num(s.weak)*2))}
  function macroAgent(){var m=market(),r=m.regime||{},breadth=num(r.breadth||r.score),leaders=num(r.leaders),weak=num(r.weak),valid=num(m.validQuotesCount||m.frontendValidQuotesCount);var score=50;if(breadth)score+=((breadth-50)*.6);score+=Math.min(15,leaders*.15);score-=Math.min(20,weak*.18);if(valid>=300)score+=5;score=Math.max(0,Math.min(100,Math.round(score)));var label=score>=70?'Risk On':score>=45?'Neutral':'Risk Off';var verdict=score>=70?'Mercato favorevole, ma evitare FOMO e titoli già tirati.':score>=45?'Mercato selettivo: prima gestire le posizioni, poi eventuali nuovi ingressi.':'Mercato difensivo: proteggere capitale e non mediare titoli deboli.';return {score:score,label:label,verdict:verdict,breadth:breadth,leaders:leaders,weak:weak}}
  function sectorAgent(){var m=market();var list=(m.sectorStrength||[]).slice().map(function(s){return {sector:s.sector||s.name||'N/D',score:sectorScore(s.sector||s.name),avgMove:num(s.avgMove),leaders:num(s.leaders),weak:num(s.weak)}}).sort(function(a,b){return b.score-a.score}).slice(0,8);if(!list.length)list=[{sector:'Semiconductors',score:55},{sector:'Software',score:55},{sector:'Healthcare/biotech',score:50},{sector:'Energy',score:50}];return list}
  function positionVerdict(r,macro){var score=50;score+=Math.max(-25,Math.min(25,r.plPct*.9));if(r.q&&String(r.q.source||'').indexOf('override')>=0)score+=3;if(/FCEL/i.test(r.p.t))score-=22;if(/INCY/i.test(r.p.t))score+=12;if(/COHR|DDOG|NOW/i.test(r.p.t)&&macro.score<55)score-=7;score=Math.max(0,Math.min(100,Math.round(score)));var action='Mantieni, non incrementare';if(score>=70)action='Mantieni / lascia lavorare';if(score<50)action='Monitorare, niente incremento';if(score<38)action='Difensiva: ridurre su rimbalzi';if(score<28)action='Speculativa: nessuna mediazione';var why=[];why.push(r.plPct>=0?'sopra PMC':'sotto PMC');if(macro.score<55)why.push('macro selettiva');if(/FCEL/i.test(r.p.t))why.push('titolo molto speculativo');if(/INCY/i.test(r.p.t))why.push('miglior profilo relativo');return {score:score,action:action,why:why.join(' · ')}}
  function htmlMetric(k,v,c){return '<div class="metric"><small>'+k+'</small>'+(c?'<span class="'+c+'">'+v+'</span>':v)+'</div>'}
  function macroHtml(){var a=macroAgent();return '<section id="v16-macro-agent" class="card"><div class="section-title"><h3>V16 Macro Agent</h3><span class="pill '+cls(a.score)+'">'+a.label+' '+a.score+'/100</span></div><div class="grid">'+htmlMetric('Breadth',a.breadth?a.breadth+'%':'N/D')+htmlMetric('Leader',a.leaders)+htmlMetric('Weak',a.weak)+htmlMetric('Aggressività',a.score>=70?'Alta controllata':a.score>=45?'Selettiva':'Bassa',cls(a.score))+'</div><p>'+a.verdict+'</p></section>'}
  function sectorHtml(){var list=sectorAgent();return '<section id="v16-sector-agent" class="card"><div class="section-title"><h3>Sector Rotation Agent</h3><span class="tag">Prezzi + forza relativa</span></div>'+list.map(function(s,i){return '<div class="row"><b>'+(i+1)+'. '+s.sector+'</b><span class="pill '+cls(s.score)+'">'+Math.round(s.score)+'</span></div>'}).join('')+'</section>'}
  function doctorHtml(){var macro=macroAgent(),rs=rows();if(!rs.length)return '';return '<section id="v16-position-doctor" class="card"><div class="section-title"><h3>Position Doctor</h3><span class="tag">Portfolio</span></div>'+rs.map(function(r){var v=positionVerdict(r,macro);return '<article class="card mini"><div class="section-title"><h3>'+r.p.t+'</h3><span class="pill '+cls(v.score)+'">'+v.score+'/100</span></div><div class="grid">'+htmlMetric('Live',usd(r.live))+htmlMetric('PMC',usd(r.p.pmc))+htmlMetric('P/L',pct(r.plPct),r.plPct>=0?'good':'bad')+htmlMetric('Azione',v.action,cls(v.score))+'</div><p>'+v.why+'</p></article>'}).join('')+'</section>'}
  function opportunityHtml(){var sectors=sectorAgent(),top=sectors[0];return '<section id="v16-opportunity-agent" class="card"><div class="section-title"><h3>Opportunity Radar</h3><span class="tag">Bozza decisionale</span></div><p>Priorità: cercare titoli non troppo estesi nei settori con score alto. Settore più forte ora: <b>'+(top?top.sector:'N/D')+'</b>.</p><p>Prossimo step: collegare news, earnings, macro calendar e catalyst specifici prima di dare un voto operativo definitivo.</p></section>'}
  function key(){var ma=macroAgent(),rs=rows();return page()+'|'+ma.score+'|'+rs.map(function(r){return r.p.t+':'+r.plPct.toFixed(2)}).join('|')}
  function removeDupes(id){var all=document.querySelectorAll('#'+id);for(var i=1;i<all.length;i++)all[i].remove()}
  function injectHome(force){if(page()!=='home')return;var k=key();if(!force&&k===lastHomeKey&&$('#v16-macro-agent'))return;lastHomeKey=k;['v16-macro-agent','v16-sector-agent','v16-position-doctor','v16-opportunity-agent'].forEach(function(id){var el=$('#'+id);if(el)el.remove()});var pg=$('.page');if(!pg)return;var wrap=document.createElement('div');wrap.id='decision-agents-bundle';wrap.innerHTML=macroHtml()+sectorHtml()+doctorHtml()+opportunityHtml();var anchor=$('#v17-synth-agent');if(anchor&&anchor.parentNode)anchor.parentNode.insertBefore(wrap,anchor.nextSibling);else pg.appendChild(wrap)}
  function injectPortfolio(force){if(page()!=='portfolio')return;var k=key();if(!force&&k===lastPortfolioKey&&$('#v16-position-doctor'))return;lastPortfolioKey=k;['v16-position-doctor','v16-opportunity-agent'].forEach(function(id){var el=$('#'+id);if(el)el.remove()});var pg=$('.page');if(!pg)return;var wrap=document.createElement('div');wrap.id='decision-agents-portfolio';wrap.innerHTML=doctorHtml()+opportunityHtml();pg.appendChild(wrap)}
  function run(force){setTimeout(function(){injectHome(!!force);injectPortfolio(!!force);['v16-macro-agent','v16-sector-agent','v16-position-doctor','v16-opportunity-agent'].forEach(removeDupes)},600)}
  window.addEventListener('load',function(){run(true)});
  window.addEventListener('hashchange',function(){lastHomeKey='';lastPortfolioKey='';run(true)});
  window.addEventListener('storage',function(){lastHomeKey='';lastPortfolioKey='';run(true)});
})();
